version: '3.8'
services:
  db:
    container_name: todo-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=todo-password
      - POSTGRES_DB=todo
    ports:
      - '5432:5432'
    volumes:
      - todo_db:/var/lib/todo-postgresql/data
volumes:
  todo_db:
    driver: local
